### ISSUE TITLE
Full SQL mode - fetch more records

### ISSUE THREAD

**Issue by oasisk** [zinclabs/zincobserve#106]
### Which Zinc Observe functionalities are relevant/related to the feature request?

logs search

### Description

- [x] Full sql mode to support limiting number of records to be fetched
- [x] Add support to fetch next x records based on offset

### Proposed solution

Add support to fetch next x records based on offset

### Alternatives considered

NA

**Comment by hengfeiyang** [comment]
I added a default limit of 1000 if there is no limit with full sql_mode.

**Comment by hengfeiyang** [comment]
and for 

```
Add support to fetch next x records based on offset
```

No problem, you can write offset in you SQL, like this:

```
select * from table where a=1 offset 100 limit 100
```
