### ISSUE TITLE
Root user can't manage new organization

### ISSUE THREAD

**Issue by eddyyuen** [zinclabs/zincobserve#123]
### Which ZincObserve functionalities are relevant/related to the feature request?

users

### Description

We have many organizations，but  root user can't manage them .

### Proposed solution

Root user can manage organization's admin user

### Alternatives considered

no

**Comment by hengfeiyang** [comment]
We plan to add a feature that let user can add an admin user for other organizations.

**Comment by hengfeiyang** [comment]
impled
