### ISSUE TITLE
Search endpoint has default field "_timestamp" in context mode

### ISSUE THREAD

**Issue by eddyyuen** [zinclabs/zincobserve#129]
### Which ZincObserve functionalities are the source of the bug?

logs search

### Is this a regression?

Yes

### Description

Remove the default  "_timestamp" field  when use context mode.

**Comment by hengfeiyang** [comment]
That is because we need use `_timestamp` to do the data sort, but you haven't select the field.

In SQL the order field must in select field. so, if you don't select `_timestamp`, I will auto add it in select.
