### ISSUE TITLE
UI:message column supports line break and show full information

### ISSUE THREAD

**Issue by hanqian200705** [zinclabs/zincobserve#130]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

The message column in the query results supports line break expansion display to show full information, making it easier to use similar to zincsearch.

The current floating tips retain the original format of the message, but it seems not very convenient to use.

### Proposed solution

Provide a switch to support displaying the results in different forms.

### Alternatives considered

The message in the detail panel supports the original text format to be expanded.

**Comment by bjp232004** [comment]
Thank you for raising this issue. 

We have enhanced the user interface and displayed more data in the visible area, we have truncated the value. Full text will be visible on hover or by clicking on a row, you will get full details. Please find below a screenshot for the same.

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/551527/220549946-8ab80b8e-2969-416e-b404-eb1d8c69c283.png">

**Comment by hanqian200705** [comment]
@bjp232004 Thanks，  Can the log  in the visible area support formatted text? 
When the log displayed in a floating window is too long it cannot be displayed completely and cannot be copied either.

**Comment by hengfeiyang** [comment]
I talked to @hanqian200705 there is two question:

 - format
    his logs are multiple lines, it looks like we deleted the original format. it can't show new line and indent.
- copy
    it's too complex to copy a log to open a new dialog. he prefers shows under the line, like ZincSearch.

<img width="858" alt="WechatIMG105" src="https://user-images.githubusercontent.com/1628250/221157364-f53c3053-4363-4d94-8cf5-dd1db0fc3517.png">

The tips give us the original format of logs. it has new line break and indent.

<img width="1021" alt="WechatIMG107" src="https://user-images.githubusercontent.com/1628250/221158533-be40c235-f668-4cf8-96e3-d5784ce45eea.png">

but in our UI everything in one line.

**Comment by hanqian200705** [comment]
Display table content with an additional approach.
<img width="204" alt="image" src="https://user-images.githubusercontent.com/4269408/221162574-65395e9b-8fef-4ee7-b6fa-a48508f87c15.png">

**Comment by bjp232004** [comment]
Tried to format the content on detail view but behaviour is not consistent with all data so might not be able to enable formatted text on detail view. Please find below screen shot.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/551527/222127975-02b9cf34-8a7d-4885-b5a4-d1e31bc3c666.png">

**Comment by hengfeiyang** [comment]
It can show format now in the new panel.
