### ISSUE TITLE
UI bug: after startup, only time and message are displayed,

### ISSUE THREAD

**Issue by colorado666** [zinclabs/zincobserve#147]
### Which ZincObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

By default, only the message field is displayed, but message has no value, resulting in a blank interface. and all other columns cannot be displayed normally.

### Please provide the version you discovered this bug in (check about page for version information)

```true
version v0.1.5
8c870fea9bd794e96a97aed299e5600ba6edd052
```

**Comment by hengfeiyang** [comment]
Can you give a screenshot? thanks

**Comment by colorado666** [comment]
<img width="1585" alt="截屏2023-02-23 00 18 48" src="https://user-images.githubusercontent.com/1509769/220689135-e4493e18-81fe-4908-841a-eddd222eb2b2.png">

**Comment by hengfeiyang** [comment]
@bjp232004 This user's stream has a message field, but the value is empty. so in the UI just a timestamp.

**Comment by prabhatsharma** [comment]
@colorado666 What did you expect to see instead of timestamp and message fields?
