### ISSUE TITLE
Create user also create  another  "default" organization

### ISSUE THREAD

**Issue by eddyyuen** [zinclabs/zincobserve#148]
### Which ZincObserve functionalities are the source of the bug?

users

### Is this a regression?

Yes

### Description

should first check whether this "default" name exists

**Comment by oasisk** [comment]
@eddyyuen can you please add exact steps to reproduce the issue?I am unable to reproduce the issue.

**Comment by eddyyuen** [comment]
> @eddyyuen can you please add exact steps to reproduce the issue?I am unable to reproduce the issue.

1. Run ZincObserve with default root user admin@zo.com
2. POST http://127.0.0.1:5080/api/default/users
3.  `{
    "email": "user@zo.com",
    "first_name": "eddy",
    "last_name": "eddy",
    "password": "12345678",
    "role": "admin"
}`
4.  Login ,you will see 2 "default" organizations.
