### ISSUE TITLE
UI: User page not only displays the data of the current organization

### ISSUE THREAD

**Issue by eddyyuen** [zinclabs/zincobserve#149]
### Which ZincObserve functionalities are the source of the bug?

users

### Is this a regression?

Yes

### Description

User page not only displays the data of the current organization.

### Please provide a link to a minimal reproduction of the bug

/users

**Comment by bjp232004** [comment]
@eddyyuen Thank you for raising this issue. Can you please provide more details about what you can see?

**Comment by eddyyuen** [comment]
### deafult organization
![default](https://user-images.githubusercontent.com/9354119/220824628-a42f3401-b6d0-44b9-bd49-53bd383736ee.png)

### deafult2 organization
![default2](https://user-images.githubusercontent.com/9354119/220824631-33befb68-75fe-46a9-b1fe-81b2a2dd4ae7.png)

### deafult3 organization
![default3](https://user-images.githubusercontent.com/9354119/220824634-a5d29545-3c1a-43c5-ab17-cbc5201446e5.png)

### an1 organization
![an1](https://user-images.githubusercontent.com/9354119/220824646-ea3805a7-31f4-4ba4-9ea0-03fcd3fb72c9.png)

**Comment by hengfeiyang** [comment]
@eddyyuen I tested just create one user for new organization, it will only list in the new organization. if you create the same user for different organizations?
