### ISSUE TITLE
UI：Time condition query supports precision to the second

### ISSUE THREAD

**Issue by hanqian200705** [zinclabs/zincobserve#163]
### Description

Time condition query supports precision to the second.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/4269408/221460718-6a635166-70a1-40b1-ad0e-f2c9e7e02cc1.png">

The current result is empty.

### Proposed solution

Time condition query supports precision to the second, It will be very useful for large-scale data scenarios.

### Alternatives considered

No

**Comment by hengfeiyang** [comment]
User can select a time range like: `10:30:08 - 10:30:30`, but we don't support second in the UI, so the query will become `10:30 - 10:30`, and the SQL will be: `select * from table where _timestamp >= '10:30' and _timestamp < '10:30'`, at the end, the result is empty.

**Comment by hengfeiyang** [comment]
done. we are support second now.
