### ISSUE TITLE
Can't run on Intel N5105

### ISSUE THREAD

**Issue by mohshami** [zinclabs/zincobserve#174]
### Which ZincObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I'm trying to run ZincObserve on my home server which is a an Intel N5105 mini PC. It's running NixOS 22.11. When I try to run the AMD64 binary I get the following error
-bash: ./zincobserve: No such file or directory

I temporarily switched to Ubuntu server 22.04 and now get the following
Illegal instruction (core dumped)

I tried running the docker container on both Ubuntu and NixOS, the container just exists without any output

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.1.8
```

### Anything else?

Is there any special CPU requirement?

**Comment by hengfeiyang** [comment]
Yes, by default we enabled some CPU features, like:

```
+aes,+avx,+avx2,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2
```

Maybe this CPU doesn't support those features, Can you check which features this CPU support?

**Comment by mohshami** [comment]
Thank you so much for the quick reply.

It supports all except for AVX. Is there a way I can get it to run?

**Comment by hengfeiyang** [comment]
If you want to try, you can manually build ZincObserve yourself, I can guide you. and we will discuss how to support this type of CPU. Thanks.

**Comment by mohshami** [comment]
I would love to, I understand having that feature enabled is better, but for a small installation like mine (I only want to collect queries going to my home DNS server) it should be find

**Comment by hengfeiyang** [comment]
Sure, you can find me in Slack channel.

**Comment by hengfeiyang** [comment]
Build steps:

1. clone the project to you local.
2. change the file https://github.com/zinclabs/zincobserve/blob/main/.cargo/config.toml, and delete the feature your machine not supported.
3. install Rust `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
4. install Special version of Rust
    ```
    rustup toolchain install nightly-2023-01-26
    rustup default nightly-2023-01-26
    ```
5. install others depends: `apt-get install -y protobuf-compiler cmake gcc`
6. build: `cargo build --release`

**Comment by mohshami** [comment]
I tried with the following config.toml

```
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+aes,+sse4.2"]
```

Sadly I get the same result on NixOS, I will have to booth ubuntu on that server. Will test that later tonight

According to 

https://www.cpu-world.com/CPUs/Celeron/Intel-Mobile%20Celeron%20N5105.html

The N5105 supports SSE4.2

Will let you know once I manage to boot ubuntu on this machine

**Comment by mohshami** [comment]
Ok so instead of booting ubuntu on the machine, I ran an ubuntu docker

docker run -v $PWD:/data -it ubuntu /bin/bash

Then

ZO_ROOT_USER_EMAIL=root@example.com ZO_ROOT_USER_PASSWORD=Complexpass#123 ./zincobserve

That worked, so the binary is good, it looks like NixOS is missing a file needed to run the binary, any idea how I can find that file?

**Comment by mohshami** [comment]
So that turned out to be a NixOS thing, so the issue can be closed. Thank you so much

**Comment by yibuma** [comment]
Based on my actual test, it normally after removing AVX and AVX2.
