### ISSUE TITLE
Modify the default value of environment variable "ZO_DATA_DIR" to "./zinc_data"

### ISSUE THREAD

**Issue by eddyyuen** [zinclabs/zincobserve#184]
### Description

The default value of  "ZO_DATA_DIR" is "./data".
It will be set to "/data" in some special cases.
And the data of many other Apps will be placed in this directory.

### Proposed solution

ENV: "ZO_DATA_DIR" defaults to "./zinc_data"

### Alternatives considered

no

**Comment by hengfeiyang** [comment]
@eddyyuen How about set root data directory to `./data/zincobserve`, then the default db directory will be: `./data/zincobserve/db`

**Comment by eddyyuen** [comment]
Yeah, as long as it's not **./data**
