### ISSUE TITLE
Top N values for fields for on UI

### ISSUE THREAD

**Issue by oasisk** [zinclabs/zincobserve#207]
### Which ZincObserve functionalities are relevant/related to the feature request?

other

### Description

For easier filtering show top N values for fields from stream on UI

### Proposed solution

Add support for top N values for fields for on UI

### Alternatives considered

NA

**Comment by hengfeiyang** [comment]
Will add a new API:

Request:

```
GET /{org}/{stream}/_values?fields=field1,field2&size=10&start_time=123&end_time=123
```

Params:

- fields: must provide
- size: optional, default: 10
- start_time: optional, default: all time
- end_time: optional, default: all time

Response:

```json
{
    "took": 155,
    "hits": [
        {
            "field": "field1",
            "values": [
                {
                    "key": "value1",
                    "num": 2
                }
            ]
        }
    ]
}
```
