### ISSUE TITLE
UI：SQL encoding transmission in the request

### ISSUE THREAD

**Issue by hanqian200705** [zinclabs/zincobserve#217]
### Description

SQL  may be intercepted by a WAF gateway, so it is recommended to transmit the SQL in encoded format in the request.
<img width="984" alt="image" src="https://user-images.githubusercontent.com/4269408/223313284-1b42c6af-b8d6-434e-ba33-4b604ee47223.png">

### Proposed solution

No

### Alternatives considered

No

**Comment by hengfeiyang** [comment]
We want to design the request like this:

```
{
    "query": {
        "sql": "select * from k8s where key = 'value'",
        "from": 0,
        "size": 10,
        "sql_mode": "full"
    },
    "aggs": {
        "a1": "select * from query group by key"
    },
    "encoding": "base64"
}
```

We will add a parameter `encoding` then allow user through API to pass the SQL with base64 encoding. and if you skip the parameter or leave it empty, we will accept raw SQL.

**Comment by hengfeiyang** [comment]
done
