### ISSUE TITLE
User: Add existing user error

### ISSUE THREAD

**Issue by eddyyuen** [zinclabs/zincobserve#218]
### Which ZincObserve functionalities are the source of the bug?

users

### Is this a regression?

Yes

### Description

When we add existing user to other organizaiton:
POST http://xxx/api/default/users 400 (Bad Request)
Json deserialize error: missing field `password` at line 1 column 95

### Please provide the version you discovered this bug in (check about page for version information)

```true
version :0.2.0
docker
```

**Comment by oasisk** [comment]
@eddyyuen : Please use POST /api/{org_id}/users/{email_id} with body { "role":"member"} , updating the documentation for same.
