### ISSUE TITLE
UI: Should not highlight all entered text

### ISSUE THREAD

**Issue by eddyyuen** [zinclabs/zincobserve#219]
### Which ZincObserve functionalities are the source of the bug?

logs search

### Is this a regression?

Yes

### Description

All entered text will be highlighted.
Should only highlight the ` macthc_all ` field

![ipe](https://user-images.githubusercontent.com/9354119/223379423-63e015cd-e76e-4077-b3b3-5c5e7d50abde.png)

### Please provide the version you discovered this bug in (check about page for version information)

```true
0.2.0
```

**Comment by eddyyuen** [comment]
![ipe](https://user-images.githubusercontent.com/9354119/223379309-c067064b-026d-483c-91ae-10c6d6b6f8f7.png)

**Comment by nitindixit14** [comment]
Looks good. should be closed.
