### ISSUE TITLE
UI: irrelevant error message on logs page

### ISSUE THREAD

**Issue by bjp232004** [zinclabs/zincobserve#226]
### Which ZincObserve functionalities are the source of the bug?

logs search

### Is this a regression?

Yes

### Description

SELECT count(code) FROM “default”  where code=500 group by code

It should not display error message related to full text field

### Please provide a link to a minimal reproduction of the bug

Check description

### Anything else?

No

**Comment by nitindixit14** [comment]
Looks good. can be closed.
