### ISSUE TITLE
Expose more internal Metrics

### ISSUE THREAD

**Issue by syepes** [zinclabs/zincobserve#236]
### Description

To be able to better operate and manage ZincObserve we need to have more Prometheus Metrics about the inner components.

#### Ingester 
- Stats about the ingested records and sizes per protocol type
- WAL Storage Size stats (Usage and Limits)
- WAL Read / Write latencies

#### Querier 
- Stats and latencies about the queries
- Expose the cache Recode and Memory size per stream

#### Compactor 
- File compaction duration times and stats
- File deletion / archiving stats

#### Storage (Local and Remote)
- Metrics about the used storage space and number of files (Parquet)
- Read / Write latencies

#### Process (All components)
- Expose the standard CPU and Mem metrics of the processes

#### Cluster
- Inner cluster communication stats
- etcd Metrics and Storage size

### Alternatives considered

None

**Comment by hengfeiyang** [comment]
@syepes i will work on this item. if you have any ideas about this, you can comment.

**Comment by hengfeiyang** [comment]
## Metrics design:

### Global labels:

- cluster: `ZO_CLUSTER_NAME`
- instance: `ZO_INSTANCE_NAME`
- role: `ZO_NODE_ROLE`

### Metrics

| component | metrics name            | labels | data type | desc |
|-----------|-------------------------|--------|-----------|------|
| http      | http_incoming_requests  | endpoint, status, organization, stream, stream_type | Counter   | endpoint: /_bulk, /_json, /_multi, /_search, /_around |
| -         | http_response_time      | endpoint, status, organization, stream, stream_type  | Histogram | endpoint: /_bulk, /_json, /_multi, /_search, /_around |
| grpc      | grpc_incoming_requests  | endpoint, status, organization, stream, stream_type | Counter   | endpoint: search, event |
| -         | grpc_response_time      | endpoint, status, organization, stream, stream_type | Histogram | endpoint: search, event |
| ingestor  | ingest_records          | organization, stream, stream_type | Gauge   | - |
| -         | ingest_bytes            | organization, stream, stream_type | Gauge   | - |
| -         | ingest_wal_used_bytes   | organization, stream, stream_type | Gauge   | currently WAL total size |
| -         | ingest_wal_write_bytes  | organization, stream, stream_type | Counter   | WAL write latency |
| -         | ingest_wal_read_bytes   | organization, stream, stream_type | Counter   | WAL read latency |
| querier   | query_cache_limit_bytes | - | Gauge   | - |
| -         | query_cache_used_bytes  | organization, stream, stream_type | Gauge   | - |
| -         | query_cache_files       | organization, stream, stream_type | Gauge   | - |
| -         | query_cache_records     | organization, stream, stream_type | Gauge   | TODO |
| compactor | compact_used_time       | organization, stream, stream_type | Counter | - |
| -         | compact_merged_files    | organization, stream, stream_type | Counter | - |
| -         | compact_merged_bytes    | organization, stream, stream_type | Counter | - |
| -         | compact_delay_hours     | organization, stream, stream_type | Gauge   | - |
| -         | deletion / archiving    |-                                  | -       | TODO |
| storage   | storage_original_bytes  | organization, stream, stream_type | Gauge   | Storage metrics will be updated regularly. |
| -         | storage_compressed_bytes | organization, stream, stream_type | Gauge  | - |
| -         | storage_files           | organization, stream, stream_type | Gauge   | - |
| -         | storage_records         | organization, stream, stream_type | Gauge   | - |
| -         | storage_write_bytes     | organization, stream, stream_type | Counter   | - |
| -         | storage_read_bytes      | organization, stream, stream_type | Counter   | - |
| metadata  | meta_storage_bytes      | -                                 | Gauge   | Metadata metrics will be updated regularly. |
| -         | meta_storage_keys       | -                                 | Gauge   | - |
| -         | meta_num_nodes          | node_role                        | Gauge   | node_role |
| -         | meta_num_organizations  | -                                 | Gauge   | - |
| -         | meta_num_streams        | organization, stream_type         | Gauge   | - |
| -         | meta_num_users_total    | -                                 | Gauge   | - |
| -         | meta_num_users          | organization                      | Gauge   | - |
| -         | meta_num_functions      | organization, stream, stream_type, function_type | Gauge   | - |
| -         | meta_num_alerts         | organization, stream, stream_type | Gauge   | TODO |
| -         | meta_num_dashboards     | organization                      | Gauge   | TODO |

**Comment by syepes** [comment]
Great work on this, once it's merged I'll give it a try

**Comment by hengfeiyang** [comment]
@syepes We already implemented those metrics except `TODO`, and you can test with the image tag: `public.ecr.aws/zinclabs/zincobserve-dev:v0.2.0-6fc51a8`
