### ISSUE TITLE
Recovery alerts

### ISSUE THREAD

**Issue by oasisk** [zinclabs/zincobserve#251]
### Which ZincObserve functionalities are relevant/related to the feature request?

alerts

### Description

Today we support two kinds of alerts : Scheduled & real time.
For both kinds of alert any time condition for alert is evaluated to true we generate an alert/notification.

We need to implement recovery alert which would be sent only:

- in the previous evaluation alert evaluated to true
- in current evaluation it evaluates to false.

Open questions : 

- After recovery alert , should we keep alert active , and keep evaluating it , to check if recovery was false positive? 
- Any addition information to be captured for an evaluation to quality as recovery alert?

### Proposed solution

alerter to add recovery alerts

### Alternatives considered

NA

**Comment by syepes** [comment]
It would also be great to control the recovery delay to prevent false positive / flapping events

**Comment by prabhatsharma** [comment]
Ideally, this should be part of the alerting system. Prometheus alertmanager has a config 
```
send_resolved: true
```
that allows configuring this.

**Comment by fclairamb** [comment]
Could you explain how this is resolved and how we can do it?
