### ISSUE TITLE
Save view when i selected some fields

### ISSUE THREAD

**Issue by hengfeiyang** [zinclabs/zincobserve#256]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

Every time I need to pick up the fields that I want to see. we should give a method to let the user save the view, it will be better.

### Proposed solution

Provider a view management, or, just store the last select view in local storage for each stream, the UX will be better.

### Alternatives considered

--

**Comment by iyikai** [comment]
I would like to contribute this feature

**Comment by hengfeiyang** [comment]
@iyikai thanks
