### ISSUE TITLE
Dashboard datastream select panel fuzzy search and real-time update function

### ISSUE THREAD

**Issue by Mashull** [zinclabs/zincobserve#257]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

This selector component hopes to support fuzzy search and real-time update functions.
![image](https://user-images.githubusercontent.com/118787336/224460893-723e373f-b6b2-4dfd-b35a-021ab2565799.png)

### Proposed solution

This selector component hopes to support fuzzy search and real-time update functions.

### Alternatives considered

Nothing

**Comment by nitindixit14** [comment]
Looks good. can be closed.
