### ISSUE TITLE
The log display interface crashes

### ISSUE THREAD

**Issue by Mashull** [zinclabs/zincobserve#258]
### Which ZincObserve functionalities are the source of the bug?

logs search

### Is this a regression?

Yes

### Description

zincobserve version: 0.2.0
--- 
I first click on the stream selector, then press the backspace key, and the entire log display panel disappear.
![image](https://user-images.githubusercontent.com/118787336/224461040-e76d3575-b8ee-41b1-b085-ef65ac092614.png)

![image](https://user-images.githubusercontent.com/118787336/224461118-c25dd457-72fc-4e8b-8b42-5d8ff0bfc5aa.png)

**Comment by bjp232004** [comment]
After implementing type ahead search, not able to reproduce this issue. Please let me know if you are still facing issue after next release.

**Comment by hengfeiyang** [comment]
fixed
