### ISSUE TITLE
Relative time filter function is doesn't work well

### ISSUE THREAD

**Issue by Mashull** [zinclabs/zincobserve#261]
### Which ZincObserve functionalities are the source of the bug?

logs search

### Is this a regression?

Yes

### Description

zincobserve version: 0.2.0

1. Perpare some test data
![image](https://user-images.githubusercontent.com/118787336/224470273-8b665bbe-6076-4765-a209-838dc2c0f2f3.png)

2. wait a few minutes

3. Relative time select  Day (1,2...) , the log data display is correctly

4. Then Relative time select Minute 1, the log data is still displayed, but obviously not in this time range
![image](https://user-images.githubusercontent.com/118787336/224470485-ab7cf53f-ca20-4050-91f0-5ac60b77f9c2.png)

### Please provide the version you discovered this bug in (check about page for version information)

```true
zincobserve version: 0.2.0
```

**Comment by hengfeiyang** [comment]
![test](https://user-images.githubusercontent.com/1628250/224471345-4d05b839-176f-4389-abb4-ab7149e7c173.gif)

Sometimes it auto trigger search, sometimes it doesn't trigger search, we need to unify the logic.

**Comment by fanbuz** [comment]
I found that the number of selections in the field list on the left seems to have something to do with the triggering of the relative time selector. When I select three fields, day 3 and hour 3 will not trigger the filter.
![image](https://user-images.githubusercontent.com/118787336/224472071-5e7f86fa-2c42-4d37-a83e-c5fe70295186.png)

**Comment by hengfeiyang** [comment]
fixed
