### ISSUE TITLE
Add new languages

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#262]
### Which ZincObserve functionalities are relevant/related to the feature request?

localization

### Description

Add following languages to the ui.

1. French
2. German
3. Dutch
4. Italian
5. Spanish
6. Portuguese
7. Japanese
8. Korean

### Proposed solution

Use locale generator to generate translations.

### Alternatives considered

Just use English

**Comment by hengfeiyang** [comment]
done
