### ISSUE TITLE
UI: Numerical view field values are not displayed

### ISSUE THREAD

**Issue by Mashull** [zinclabs/zincobserve#263]
### Which ZincObserve functionalities are the source of the bug?

logs search

### Is this a regression?

Yes

### Description

Log data detail display extraly
![image](https://user-images.githubusercontent.com/118787336/224473160-5095b6bb-52d2-46bc-95e8-eba902279c12.png)

But when I select these numeric fields, the values are not displayed correctly.
![image](https://user-images.githubusercontent.com/118787336/224473197-5bc1a92f-ffb8-4bb1-8dc3-a062974cc1d1.png)

### Please provide the version you discovered this bug in (check about page for version information)

```true
version: 0.2.0
```

**Comment by oasisk** [comment]
Reproducible for value 0

**Comment by hengfeiyang** [comment]
fixed
