### ISSUE TITLE
Support for Elastic Filebeat

### ISSUE THREAD

**Issue by gaby** [zinclabs/zincobserve#264]
### Description

I'm looking into using ZincObserve to ingest Syslog / Sflow events via Filebeat. Currently we use Filebeat -> Logstash -> ElasticSearch. Is this something that can be done with ZincObserve? 

The docs for ZincSearch have an integration section for Filebeat but it missing for ZincObserve.

### Proposed solution

Document how to use Elastic Filebeat with ZincObserve

### Alternatives considered

Using ZincSearch

**Comment by prabhatsharma** [comment]
Filebeat and any other elasticsearch compatibility features will be part of zBridge that we intend to build as an open-core company. zBridge is available today as our commercial offering.

**Comment by gaby** [comment]
Thanks
