### ISSUE TITLE
UI:The query condition editing area is not compatible with Chinese input

### ISSUE THREAD

**Issue by Mashull** [zinclabs/zincobserve#266]
### Which ZincObserve functionalities are the source of the bug?

logs search

### Is this a regression?

Yes

### Description

When I input Chinese in the editing area, a black bar will appear covering the entire input area. I tested Sogou input method and Microsoft Pinyin, both can reproduce the problem.

Sougou:
![image](https://user-images.githubusercontent.com/118787336/224518678-dddf63f2-28d2-4c08-aa08-99ec80e83a24.png)

Microsoft Pinyin:
![78a43dfae0d869f8cdabf4faa67698c](https://user-images.githubusercontent.com/118787336/224518686-3ba6fb2b-7a8b-472c-aec2-11be69fcd4d9.png)

### Please provide the exception or error you saw

```true
I tested Sogou input method and Microsoft Pinyin, both can reproduce the problem
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
zo version:0.2.0

Brower version: 
Microsoft Edge 110.0.1587.69  (latest version)
```

**Comment by oasisk** [comment]
A black line appears in SQL editor , after switching menu items or language.

**Comment by hengfeiyang** [comment]
fixed
