### ISSUE TITLE
`test_check_auth` is flaky

### ISSUE THREAD

**Issue by vvv** [zinclabs/zincobserve#269]
### Which ZincObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No idea.

### Description

`handler::grpc::auth::test_utils::test_check_auth` fails intermittently.

### Please provide a link to a minimal reproduction of the bug

```sh
cargo +nightly-2023-01-26 test test_check_auth
```

### Please provide the exception or error you saw

```true
---- handler::grpc::auth::test_utils::test_check_auth stdout ----
thread 'handler::grpc::auth::test_utils::test_check_auth' panicked at 'assertion failed: check_auth(request).is_ok()', src/handler/grpc/auth/mod.rs:103:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Please provide the version you discovered this bug in (check about page for version information)

495c49d9f94d2e4bd3321f364e59c2518c8dab74

**Comment by hengfeiyang** [comment]
There is no problem running the test in my local and CI. please clean your data directory and pull the latest code try again.
