### ISSUE TITLE
`test_index_ok` fails

### ISSUE THREAD

**Issue by vvv** [zinclabs/zincobserve#270]
### Which ZincObserve functionalities are the source of the bug?

routing

### Is this a regression?

Yes

### Description

`handler::http::router::ui::tests::test_index_ok` fails, reproducibility 100%.

### Please provide a link to a minimal reproduction of the bug

```
cargo test +nightly-2023-01-26 test_index_ok
```

### Please provide the exception or error you saw

```
---- handler::http::router::ui::tests::test_index_ok stdout ----
thread 'handler::http::router::ui::tests::test_index_ok' panicked at 'assertion failed: resp.status().is_success()', src/handler/http/router/ui.rs:70:9
```

### Please provide the version you discovered this bug in (check about page for version information)

```
495c49d9f94d2e4bd3321f364e59c2518c8dab74
```

**Comment by vvv** [comment]
Latest `main` (efea62fff2c4192f305adc9e9e047c9af80e74c6) after `cargo clean && git clean -fdx`:

```
failures:

---- handler::http::router::ui::tests::test_index_ok stdout ----
thread 'handler::http::router::ui::tests::test_index_ok' panicked at 'assertion failed: resp.status().is_success()', src/handler/http/router/ui.rs:70:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- infra::db::tests::test_delete stdout ----
thread 'infra::db::tests::test_delete' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `3`', src/infra/db/mod.rs:112:9


failures:
    handler::http::router::ui::tests::test_index_ok
    infra::db::tests::test_delete

test result: FAILED. 114 passed; 2 failed; 2 ignored; 0 measured; 0 filtered out; finished in 0.90s
```

When I ran `cargo test` the second time, only `test_index_ok` failed.

**Comment by hengfeiyang** [comment]
there is no problem running the same test in my local and CI. Maybe you need follow:

1. delete data directory from your local, it will effect the test.
2. build web assets by `cd web && npm install && npm run build`, test_index need assets exists.
