### ISSUE TITLE
Func: The data flow module does not follow the organization switch

### ISSUE THREAD

**Issue by Mashull** [zinclabs/zincobserve#277]
### Which ZincObserve functionalities are the source of the bug?

logs search

### Is this a regression?

Yes

### Description

After I switched organizations on the log module page, 
![image](https://user-images.githubusercontent.com/118787336/224903338-48b418c7-1de3-4755-b071-892706189eef.png)

Then I visit the data flow module page and find that the records are not switched.
![image](https://user-images.githubusercontent.com/118787336/224902259-9d66798a-4bc5-4928-9059-ae89e54801b9.png)

I need to click the refresh button once to complete the switch

### Please provide the version you discovered this bug in (check about page for version information)

```true
version: 0.2.0
```

**Comment by hengfeiyang** [comment]
fixed
