### ISSUE TITLE
UI: Remove organisation select from login page

### ISSUE THREAD

**Issue by hengfeiyang** [zinclabs/zincobserve#290]
### Which ZincObserve functionalities are relevant/related to the feature request?

login

### Description

Actually, we can switch organizations after login in the top organization list. at the login page shows the organization has some potential security problems and not necessary

### Proposed solution

Delete organizations select，switch in the top after login, and remember the last chosen organization in localStorage.

### Alternatives considered

No

**Comment by oasisk** [comment]
@hengfeiyang we only list organisations to which the user logging in belongs , so that user can login to any desired org.

**Comment by prabhatsharma** [comment]
I agree with Hengfei on this. Organization selection after login is a much better approach.

**Comment by hengfeiyang** [comment]
@oasisk Some users asked me why there is no organization can be select? I told them you need to input the correct username first because the organization will select by username.

**Comment by oasisk** [comment]
fixed with https://github.com/zinclabs/zincobserve/pull/298
