### ISSUE TITLE
Ingestion token : should only allow data ingestion

### ISSUE THREAD

**Issue by oasisk** [zinclabs/zincobserve#293]
### Which ZincObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

Today we allow ingestion token to be used for accessing non ingestion api's as well.

### Please provide the exception or error you saw

```true
We should only forbid  non-ingestion endpoints to be accessed using token. Basic auth with username & password should be used for same.
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.2.0
```

**Comment by hengfeiyang** [comment]
Sure, it is just for ingest.

**Comment by hengfeiyang** [comment]
tested
