### ISSUE TITLE
zincobserver的web输入SQL时报错

### ISSUE THREAD

**Issue by sangensong** [zinclabs/zincobserve#297]
### Which ZincObserve functionalities are the source of the bug?

logs search

### Is this a regression?

Yes

### Description

when I input 
```sql
select * from "t_log_http_http" where match_all('144') limit 20 offset 10
```
there is a error happened

error: sql parser error. Expected end of statement, found: limit

**Comment by hengfeiyang** [comment]
This is because the UI will auto-append a `limit 150` for the SQL.

**Comment by hengfeiyang** [comment]
@sangensong for now we disallow the limit in UI. because UI will auto append limit before send the query.

**Comment by bjp232004** [comment]
in case use passes the limit and offset in full SQL mode, the same will be used to pass in the request body.
