### ISSUE TITLE
Search request response to have custom error codes which can be used by UI to show user friendly message

### ISSUE THREAD

**Issue by oasisk** [zinclabs/zincobserve#305]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

Today we show not so user friendly messages.

### Proposed solution

- [x] Full text search field not found
- [x] 500 Internal server - 
- [x] Search field not found
- [x] Not valid SQL
- [x] Function not defined 
- [x] Parquet field non-compatible data types
- [x] Parquet file not found - metadata mismatch 
- [x] Handle function without pipe - UI 

### Alternatives considered

NA

**Comment by hengfeiyang** [comment]
You can check the error code here: https://github.com/zinclabs/zincobserve/blob/main/src/infra/errors.rs
