### ISSUE TITLE
UI: Switching pages immediately after refreshing the log interface will result in an error

### ISSUE THREAD

**Issue by Mashull** [zinclabs/zincobserve#319]
### Which ZincObserve functionalities are the source of the bug?

logs search, routing

### Is this a regression?

Yes

### Description

I clicked the browser refresh button on the log module interface, and switched to the data flow module before the data was loaded completely, and an error message would appear.
![image](https://user-images.githubusercontent.com/118787336/226238342-b9099d76-5e01-4fd6-a4f2-b5ee256d27c5.png)

Then switch back to the log module, the chart area is not displayed normally.
![image](https://user-images.githubusercontent.com/118787336/226238455-d3ce579f-8c0a-4fd7-bab0-acbd8ff8b956.png)

### Please provide the version you discovered this bug in (check about page for version information)

```true
version: 0.2.0
```

**Comment by bjp232004** [comment]
Code deployed in a lower environment.

https://www.loom.com/share/9ee598fb34f943399f0cd428a532d691

**Comment by fanbuz** [comment]
![forshow](https://user-images.githubusercontent.com/118787336/226547011-a86c3338-3282-4a23-af52-bd12b3447cb8.gif)

**Comment by bjp232004** [comment]
Thank you, I have fixed this issue and raised a PR for same.

**Comment by nitindixit14** [comment]
This issue has closed. working as expected.
