### ISSUE TITLE
Partition key not working

### ISSUE THREAD

**Issue by hengfeiyang** [zinclabs/zincobserve#368]
### Which ZincObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I set a partition key in stream settings. but the logs not stored use the partition key.

- [x] for ingestion
- [x] for compaction

**Comment by oasisk** [comment]
fixed by https://github.com/zinclabs/zincobserve/pull/370

**Comment by hengfeiyang** [comment]
fixed
