### ISSUE TITLE
default labels should be same as the field name

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#369]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

No

### Description

Currently default field labels are being capitalized and spaced. They should be same as the field name by default.

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/4242188/227240676-09b1a055-480b-45e6-a1a6-efe6679ca52c.png">

**Comment by ktx-kirtan** [comment]
We can close this as we do not need changes and need the current approach as is
