### ISSUE TITLE
Cannot refresh http://localhost:5080/web/dashboards/add_panel?dashboard=4670378015

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#411]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

Refreshing http://localhost:5080/web/dashboards/add_panel?dashboard=4670378015 gives 404

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.3.0
```

**Comment by ktx-kirtan** [comment]
@prabhatsharma This is working fine for us when we run `npm run dev` from the web folder. 

@bjp232004 Can you please share any inputs why that might be happening in the full build as we are not aware about the build

**Comment by hengfeiyang** [comment]
fixed
