### ISSUE TITLE
show legends should be on by default in add panel

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#419]
### Which ZincObserve functionalities are relevant/related to the feature request?

dashboards

### Description

show legends is not selected by default. 

### Proposed solution

make show legends selected by default.

### Alternatives considered

switch on legends every time I create a panel

**Comment by ktx-kirtan** [comment]
@prabhatsharma In that case, it will show the legends even when y axis will have only single value

![image (13)](https://user-images.githubusercontent.com/124270523/227710186-4e3e4acf-ceba-4ab1-9ad5-81867a998a51.png)

Can you please confirm?

**Comment by prabhatsharma** [comment]
yes
