### ISSUE TITLE
Need "is" operator in filter

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#424]
### Which ZincObserve functionalities are the source of the bug?

dashboards, alerts

### Is this a regression?

Yes

### Description

<img width="666" alt="image" src="https://user-images.githubusercontent.com/4242188/227715512-b4388b2a-0fe5-4e6a-9136-a3770a2f3a03.png">

This is required to specify conditions like is null or is not null

**Comment by hengfeiyang** [comment]
@prabhatsharma need `is` and `is not`

**Comment by ktx-keshavi** [comment]
@hengfeiyang @prabhatsharma , for "is" and "is not" will only be used for the NULL checking, right? So, we will hide the value input when "is" and "is not" is selected. We will put "Is Null" and "Is Not Null" in the dropdown. 

Do let me know if we need anything else

**Comment by hengfeiyang** [comment]
fixed
