### ISSUE TITLE
Incorrect redirection after create dashboard

### ISSUE THREAD

**Issue by bjp232004** [zinclabs/zincobserve#436]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

The user was redirected to the incorrect dashboard after creating a dashboard. Tried to create new dashboard in alpha1 environment and was redirected to a blank dashboard.

### Please provide a link to a minimal reproduction of the bug

https://alpha1.cloud.zinclabs.dev/dashboards/view?dashboard=

### Please provide the exception or error you saw

```true
Steps:
- Login to alpha1
- Go to Dashboard > Add Dashboard
- Provide Dashboard name and submit.
- User will be redirected to blank dashboard.
```

**Comment by hengfeiyang** [comment]
fixed
