### ISSUE TITLE
UI: Dashboard supports import and export

### ISSUE THREAD

**Issue by hanqian200705** [zinclabs/zincobserve#438]
### Which ZincObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Dashboard supports import and export .

### Proposed solution

No

### Alternatives considered

No

- [x] Convert dashboard request & response to json
- [x] Support import export of Dashboards

**Comment by vvv** [comment]
> - [x] Convert dashboard request & response to json

Addressed by #466.

**Comment by hengfeiyang** [comment]
fixed
