### ISSUE TITLE
Some minor changes of dashboard params

### ISSUE THREAD

**Issue by hengfeiyang** [zinclabs/zincobserve#452]
### Which ZincObserve functionalities are relevant/related to the feature request?

dashboards

### Description

- [x] should add params `size: 0` when fire a query, without this, backend will always return 10 records. add a `size: 0` will tell backend not use default value `10` and will response all records.
- [x] table name should use double quote
- [x] after `group by` should add `order by`, we can order by `x-axis`, with `order by` it will a bit efficient.

### Proposed solution

-

### Alternatives considered

-

**Comment by gaby** [comment]
I ran into this issue when using the Data Table, it always returns 10 records and there is no option to change/save it

**Comment by hengfeiyang** [comment]
@gaby fixed, default will be `1000`, and you can custom SQL, add `limit 100`

**Comment by gaby** [comment]
@hengfeiyang Thanks! Looking forward to the next release 😁
