### ISSUE TITLE
Add source on dashboard

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#453]
### Which ZincObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Currently panels can be created only based on logs. If we want to build panels based on metrics or traces, it is not possible.

### Proposed solution

We need a section to select source for dashboards. Sources are:

1. logs
2. metrics
3. traces

The fields column should start with:

- Stream type
    - drop down to select stream type
 - Stream
     - current drop down to select stream
 - Fields
     - Current list of fields

To fetch streams belonging to metrics:

https://domain.com/api/default/streams?type=logs&fetchSchema=true

To get data.

https://domain.com/api/default/_search?type=metrics

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
fixed
