### ISSUE TITLE
UI: API to get the user list is failing from UI on Users page

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#46]
Below API endpoint is failing as 404 from UI. This results in non listing of user data on the UI

http://localhost:5080/api/org_users/default?page_num=0&page_size=1000&sort_by=email&desc=false&name=

**Comment by hengfeiyang** [comment]
It looks this is the wrong API, we have no this API. the user list API is: `/api/{org_id}/users`

**Comment by prabhatsharma** [comment]
Line 34 in users.ts needs to be changed to:

`/api/${org_identifier}/users?page_num=${page_num}&page_size=${page_size}&sort_by=${sort_by}&desc=${desc}&name=${name}`

We however need to have this changed based on env variable.
