### ISSUE TITLE
UI: dashboards  add data points on the line chart，display X and Y axis information

### ISSUE THREAD

**Issue by hanqian200705** [zinclabs/zincobserve#461]
### Which ZincObserve functionalities are relevant/related to the feature request?

dashboards

### Description

 It is recommended to add data points on the line in a line chart. 
When hovering over the chart, both X and Y axis information should be displayed. Currently, only the Y-axis information is displayed.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/4269408/228714052-a2978078-1b53-4017-8aa3-20abac79d03b.png">

### Proposed solution
1.Display both X and Y axis values on the data points.
2.Display a short time format on the X axis, while displaying the complete time format on the data points.
<img width="545" alt="image" src="https://user-images.githubusercontent.com/4269408/228717017-21a19d41-19b0-4f24-b9d5-9e14b22da8c5.png">

### Alternatives considered

no

**Comment by ktx-kirtan** [comment]
@hengfeiyang This should be solved by https://github.com/zinclabs/zincobserve/issues/434#issuecomment-1486849767 This has already been completed

**Comment by hengfeiyang** [comment]
Thanks, i will test latest version.

**Comment by prabhatsharma** [comment]
Completed in v0.4.1
