### ISSUE TITLE
date and time range with absolute selection value has recursive callbacks

### ISSUE THREAD

**Issue by ktx-keshavi** [zinclabs/zincobserve#470]
### Which ZincObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

When we select any value with the absolute tab, it is going into the recursive callback.

![image](https://user-images.githubusercontent.com/124258826/228888085-93699a4c-89d3-44c1-986d-9e76a1ddc831.png)

This is also affecting the dashboards as well

**Comment by prabhatsharma** [comment]
Completed in v0.4.1
