### ISSUE TITLE
returning errors for ingestion for each record that is not ingested

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#480]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

During the ingestion currently, if errors happen a consolidated message is reported that how many records failed. ZO does snot return each record that failed. Returning details of each failed record will allow for better retries.

### Proposed solution

use elasticsearch kind of error reporting failure.

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
fixed
