### ISSUE TITLE
The dashboard cannot be saved after upgrading the version 0.3.2

### ISSUE THREAD

**Issue by e8tg001** [zinclabs/zincobserve#495]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

0.3.1 => 0.3.2 ,After the version is upgraded
0.3.1 version dashboard data disappeared.
Version 0.3.2 dashboard, unable to save new dashboard data.
![1](https://user-images.githubusercontent.com/40289299/229681286-3ad7d511-17c9-420f-9b1c-5a064e4d78b6.png)
![2](https://user-images.githubusercontent.com/40289299/229681318-69f9a282-b603-4d18-8065-934af13a086a.png)
![3](https://user-images.githubusercontent.com/40289299/229681349-0f6b571e-46b1-43c9-b822-10d4df95681d.png)

### Please provide the version you discovered this bug in (check about page for version information)

```true
version:v0.3.2
hash:a12c252ad044792cdba4b8de26831f8e689b91f6
```

**Comment by hengfeiyang** [comment]
Yes, before the update to v0.3.2 you should delete dashboards we wrote this notice in the release note https://github.com/zinclabs/zincobserve/releases/tag/v0.3.2

For now, you can use version v0.3.1 to delete dashboards, then upgrade to v0.3.2 again. 
Or, wait for next release, I will add a command for clear dashboards

**Comment by e8tg001** [comment]
Thanks for the reminder！
Delete the old version of the dashboard data first, then upgrade the version, and then rebuild the dashboard data? 
Otherwise, because of the data structure problem, cannot create this version of the dashboard?
Is that so?

**Comment by hengfeiyang** [comment]
i am not sure your question, can you talk to me in WeChat group?

**Comment by e8tg001** [comment]
Ok

**Comment by hengfeiyang** [comment]
That's because of the upgrade, rollback to v0.3.1 and then delete all dashboards, then upgrade to v0.3.2 again. it fixed.
