### ISSUE TITLE
Top 10 values for filtering

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#504]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

As a user I should be able to filter based on top values of a particular field. 

e.g. 1 - Field is http_method . I should be able to get the values of GET, POST, PUT, etc when I click/hover on the field list on the left hand side where I can pick one or more of GET, POST, PUT, etc.

e.g.2 - Field is ip_address. I should be able to see top 10 IP addresses that I can use to filter the results. I should be able to select one or more IP addresses.

### Proposed solution

I should be able to get a pop-up when I click the field that shows me top 10 values

<img width="360" alt="image" src="https://user-images.githubusercontent.com/4242188/229972243-83f0b597-807a-431c-a9cf-822719d776b6.png">

Following issue has API details - https://github.com/zinclabs/zincobserve/issues/207

### Alternatives considered

Manually type the values that I want to filter.

**Comment by hengfeiyang** [comment]
fixed
