### ISSUE TITLE
Support for Zstd v1.5.5

### ISSUE THREAD

**Issue by gaby** [zinclabs/zincobserve#511]
### Which ZincObserve functionalities are relevant/related to the feature request?

other

### Description

Currently ZO has a pinned version of zstd that is several versions behind. Zstd v1.5.5 was released this week with a corruption bug fix.

Zstd: https://github.com/facebook/zstd/releases/tag/v1.5.5
Zstd-rs: https://github.com/gyscos/zstd-rs/pull/220

### Proposed solution

Update your cargo toml using the suggestion from the package:

https://github.com/gyscos/zstd-rs#manually

```toml
# Cargo.toml

[dependencies]
zstd = "0.12"
```

### Alternatives considered

N/a

**Comment by hengfeiyang** [comment]
@gaby updated, thanks
