### ISSUE TITLE
GRPC Endpoint

### ISSUE THREAD

**Issue by gopinathcs** [zinclabs/zincobserve#523]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search, ingestion

### Description

Hi Team, We are evaluating ZincObserve for our logs and some other use-case. One of the requirements its to have GRPC endpoint to speed up request and response.

I did see grpc endpoint but couldn't see docs for it. Also check test files for it. Is there some example work in process SDK etc for GRPC. 

Regards
Gopi

### Proposed solution

N/A

### Alternatives considered

N/A

**Comment by prabhatsharma** [comment]
What are the other use cases apart from logs. ZO uses grpc for inter-node/pod communication and HTTP for browser/user->ZO. Can you provide more details around your use case. It will allow us to better help you.

**Comment by gopinathcs** [comment]
We are thinking about using it for conversational Episode memory, that means it will be queried in multi times for each utterance from user and thousands of users at a time. 

Latency and thought put for queries, is top of the list.

**Comment by prabhatsharma** [comment]
ZO is not the right product for this use case. You are looking for an index based solution maybe even a vector database. Check weaviate, qdrant or milvus.
