### ISSUE TITLE
Selecting dashboards should be possible only horizontally

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#531]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

No

### Description

![image](https://user-images.githubusercontent.com/4242188/230846703-df421ae6-d2dc-4765-9c77-ba2fab1e8228.png)

### Anything else?

Its fixed in the log search page.

**Comment by ktx-kirtan** [comment]
This is completed with #539
