### ISSUE TITLE
x-axis if its time should be horizontal and not slant

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#532]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/4242188/230847407-b12d4ea6-4eef-4881-9be1-22392723b54e.png">

**Comment by ktx-kirtan** [comment]
@prabhatsharma This was done, but would suggest making it slant again due to #655
