### ISSUE TITLE
UI: Add kinesis firehose as an option for ingestion

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#537]
### Which ZincObserve functionalities are relevant/related to the feature request?

ingestion

### Description

ZincObserve now supports kinesis firehose HTTP endpoint as ingestion option. This API is located at https://domain.com/aws/org/stream/_kinesis_firehose

Its authentication mechanism requires an `access key` instead of user id and password which is base64(userid:password)

### Proposed solution

Add one more option next to fluentbit, vector, etc.

### Alternatives considered

None

**Comment by bjp232004** [comment]
It will display two parameters :
URL:<https://domain.com>/aws/org/stream/_kinesis_firehose
X-Amz-Firehose-Access-Key: base64(username:passcode)

**Comment by prabhatsharma** [comment]
released in v0.4.1
