### ISSUE TITLE
[ui] TypeError: Cannot read properties of undefined (reading 'state') at getDefaultOrganization

### ISSUE THREAD

**Issue by vvv** [zinclabs/zincobserve#576]
### Which ZincObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Steps to reproduce

1. Start ZincObserve locally:
   - Run `(cd web; npm install)`
   - `cargo run` in another terminal
2. Go to Logs
3. Behold an uncaught exception error in the JavaScript console

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/17462/232032097-df656dee-5bd9-4673-b89f-402b1ca39854.png">

### Version

[`v0.3.2-77-g4f1c5dd`](https://github.com/zinclabs/zincobserve/commit/4f1c5dd53d6d0262c1c3fc45436c9b8bb0e190c6)

**Comment by prabhatsharma** [comment]
Completed in v0.4.1
