### ISSUE TITLE
设置生命周期运行报错 (Set the life cycle to run an error)

### ISSUE THREAD

**Issue by cooting-cn** [zinclabs/zincobserve#590]
### Which ZincObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

启动运行服务之后，再设置ZO_DATA_LIFECYCLE的生命周期变量，启动报错
(After starting and running the service, set the life cycle variable of ZO_DATA_LIFECYCLE and start reporting an error)

 thread 'main' panicked at 'common config error: data lifecyle disallow set period less than 3 days.', src/infra/config.rs:313:9

 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.3.2
```

**Comment by cooting-cn** [comment]
[2023-04-18T05:57:10Z INFO  zincobserve] Starting ZincObserve v0.3.2

 [2023-04-18T05:57:10Z INFO  tracing::span] db:user:root_user_exists;

 thread 'tokio-runtime-worker' panicked at 'sled db dir create failed: Io(Custom { kind: Other, error: "could not acquire lock on \"./data/zincobserve/db/db\": Os { code: 11, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" })', src/infra/db/sled.rs:316:50

 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 Error: channel closed

**Comment by hengfeiyang** [comment]
It already give you the error, you can’t set value small than 3.

and second error is you already have one instance started, you can’t use same db start two instances
