### ISSUE TITLE
Histogram infects time range selected

### ISSUE THREAD

**Issue by huangjun0124** [zinclabs/zincobserve#595]
### Which ZincObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

In the log search panel, default the Histogram switch is on.
select RELATIVE time to 1 Week or more, click Run Query, it will send multiple request, and the time selected will automatically become ABSOLUTE Past 1 day,  like【2023-04-17 14:00:00 - 2023-04-18 14:00:00】with the current time【2023-04-19 14:38:00】,
which lead to search result not corret.

But with Histogram switch turned off, everything will be allright. time range selected will remain RELATIVE and the browser sends only 1 request so that search result is good.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.3.2
Commit Hash: a12c252
Build Date: 2023-03-31T19:18:15Z
OS: linux amd64
```

**Comment by keithlovingcats** [comment]
just tried with docker version, the behavior is the same

**Comment by hengfeiyang** [comment]
This issue should already fixed in develop version. you can try develop version: https://gallery.ecr.aws/zinclabs/zincobserve-dev

**Comment by keithlovingcats** [comment]
> This issue should already fixed in develop version. you can try develop version: https://gallery.ecr.aws/zinclabs/zincobserve-dev

Any released executable i can find instead of docker image?

**Comment by hengfeiyang** [comment]
@huangjun0124 you can try this tag:

```
public.ecr.aws/zinclabs/zincobserve-dev:v0.3.2-21cb4ff
```

**Comment by keithlovingcats** [comment]
> @huangjun0124 you can try this tag:
> 
> ```
> public.ecr.aws/zinclabs/zincobserve-dev:v0.3.2-21cb4ff
> ```

Tried this docker image, seems fixed.
Any idea when will this be released?

**Comment by hengfeiyang** [comment]
This week

**Comment by keithlovingcats** [comment]
This version seems to have another bug: the scroll down is not showing pages, not fetching more data

**Comment by hengfeiyang** [comment]
Can you join our Wechat Group? I can't reproduce your question.

**Comment by keithlovingcats** [comment]
> Can you join our Wechat Group? I can't reproduce your question.

request sent
