### ISSUE TITLE
Create function and delete stream returning 404

### ISSUE THREAD

**Issue by bjp232004** [zinclabs/zincobserve#608]
### Which ZincObserve functionalities are the source of the bug?

streams

### Is this a regression?

Yes

### Description

Create function and delete stream api returning 404

**Comment by mrabdibdi-anvil** [comment]
Hello, 

simply dropping this here, (didn't find in the open api documentation)

To delete a stream with a metrics type (in a context using prometheus remote write ingestion)

```bash
curl --location --request DELETE 'http://localhost:5080/api/{orgid}/{stream_name}?type=metrics' \
--header 'Authorization: Basic __YOUR_BASE64_CREDS__'
```

Without the `?type=metrics`, the API returns 404 not found
