### ISSUE TITLE
Query paging is not functional

### ISSUE THREAD

**Issue by huangjun0124** [zinclabs/zincobserve#620]
### Which ZincObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

version [v0.4.1]
when logs count is bigger than 150, scroll mouse down to the bottom, "Waiting for response" tip will popup,
the chrome Network also shows request, but the ui does not display new data.
In other words, paging in search ui is not functional anymore.
This should be urgent, please check.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.4.1
OS: linux amd-x64
```

**Comment by omkarK06** [comment]
@huangjun0124 I tried but not able to reproduce this issue. Can you provide any additional information to reproduce this issue.

**Comment by keithlovingcats** [comment]
> @huangjun0124 I tried but not able to reproduce this issue. Can you provide any additional information to reproduce this issue.

I tried the new released version 0.4.1, both Chrome and Edge occurs the same issue, clear browser data and reopen is still the same.
When the queried data is a lot, when you scroll down to bottom, paging is not happening.

**Comment by keithlovingcats** [comment]
Just tried docker version with totally brand new incoming logs, and still the same.

**Comment by keithlovingcats** [comment]
> @huangjun0124 I tried but not able to reproduce this issue. Can you provide any additional information to reproduce this issue.

Using the offical data is still the same.
Server is ubuntu 20.04 but should not matter
1. run docker
`docker run -d --name zincobserve -e ZO_DATA_DIR="/data" -p 5080:5080 \
    -e ZO_ROOT_USER_EMAIL=root@ly.com -e ZO_ROOT_USER_PASSWORD=Complexpass#123 -e ZO_TELEMETRY=false -e ZO_DATA_LIFECYCLE=3 \
    -e ZO_MAX_FILE_RETENTION_TIME=600 -e ZO_FILE_PUSH_INTERVAL=10 -e ZO_INGEST_ALLOWED_UPTO=24 \
    -e RUST_LOG=info -e ZO_FEATURE_PER_THREAD_LOCK=true\
    public.ecr.aws/zinclabs/zincobserve:v0.4.1`
2. ingest data
`curl -L https://zinc-public-data.s3.us-west-2.amazonaws.com/zinc-enl/sample-k8s-logs/k8slog_json.json.zip -o k8slog_json.json.zip
unzip k8slog_json.json.zip
curl http://localhost:5080/api/default/default/_json -i -u root@ly.com:Complexpass#123  -d "@k8slog_json.json"
`
3. open Chrome or Edge, search, scorll down to bottom, no new data is loaded,

**Comment by hengfeiyang** [comment]
Confirm, checking

**Comment by hengfeiyang** [comment]
fixed
