### ISSUE TITLE
[UI] Add user button showing error

### ISSUE THREAD

**Issue by Mashull** [zinclabs/zincobserve#628]
### Which ZincObserve functionalities are the source of the bug?

users

### Is this a regression?

Yes

### Description

When I switch to the default group, the add user button can be displayed normally, and at this time, switching to other orgs is also displayed, and then I click to refresh the page in the non-default group, the button disappears, and then redisplays after switching to the default group.
![forshow](https://user-images.githubusercontent.com/118787336/234225751-45ccae21-047a-4625-98f1-ba09d59ae794.gif)

### Please provide the version you discovered this bug in (check about page for version information)

```true
version: v0.4.1
```

**Comment by gaby** [comment]
👍🏻 I also ran into this issue after migrating to v0.4.1

**Comment by gaby** [comment]
I don't see this bug anymore @bjp232004
