### ISSUE TITLE
timstamp in dashboard is not rendering well

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#655]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/4242188/235330399-c88b20ad-cb77-435c-a077-b2d3ce4858f3.png">

**Comment by ktx-kirtan** [comment]
@prabhatsharma  Can we make it slant again? This is the only way to ensure they won't overlap.
