### ISSUE TITLE
Unable to use uppercase boolean

### ISSUE THREAD

**Issue by exgame** [zinclabs/zincobserve#703]
### Which ZincObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

ZincObserve configuration does not understand boolean staring with uppercase, for example True/False

### Please provide the exception or error you saw

```true
May 09 10:09:59 server systemd[1]: Started The ZincObserve server.
May 09 10:09:59 server zincobserve[3552825]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseBoolError', src/infra/config.rs:118:10
May 09 10:09:59 server zincobserve[3552825]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.4.2
1af2a7bea2f1eea2ade9d51f45ea9842e23a3817
2023-05-01T13:58:14Z
```

**Comment by hengfeiyang** [comment]
It means you set something should be boolean,but not, can you check your configure environments?

**Comment by exgame** [comment]
I've replaced True with true and everything seems to be working fine.

**Comment by hengfeiyang** [comment]
Yes, `The only accepted values are "true" and "false". Any other input will return an error.`

https://doc.rust-lang.org/std/primitive.bool.html#method.from_str

**Comment by hengfeiyang** [comment]
@exgame i updated the config library support uppercase boolean.

https://crates.io/crates/dotenv-config/0.1.6
