### ISSUE TITLE
Add support for assigning a stream to new users

### ISSUE THREAD

**Issue by gaby** [zinclabs/zincobserve#707]
### Which ZincObserve functionalities are relevant/related to the feature request?

users

### Description

Currently I have a test setup with one organization and multiple data streams. When creating a new user there's no way to assign a user to only 1 or more Streams, they get access to all the streams in the organization by default.

### Proposed solution

Support for assigning one, or more streams to a new user.

### Alternatives considered

Creating multiple orgs per user, but this makes searching for an admin more difficult since you have to be constantly switching between orgs/streams.

**Comment by prabhatsharma** [comment]
This will be covered in https://github.com/zinclabs/zincobserve/issues/304
