### ISSUE TITLE
Add support for specifying Trusted Root CA

### ISSUE THREAD

**Issue by gaby** [zinclabs/zincobserve#733]
### Which ZincObserve functionalities are relevant/related to the feature request?

alerts, other

### Description

Currently when setting alerts if the alerts are getting sent to a host using HTTPS and a self-signed certs it fails with a error saying the CA is not trusted.

This is a problem when running in Docker since the CA's are already bundled in the container, and there's no option to add custom ones.

### Proposed solution

Add an env variable for specifying a trusted Trusted Root CA like the variable for ETCD.

### Alternatives considered

None

**Comment by prabhatsharma** [comment]
I am not sure if we want to do this. You could always build a new docker image. Should not be too difficult. You can find the existing files at https://github.com/zinclabs/zincobserve/tree/main/deploy/build

**Comment by gaby** [comment]
@prabhatsharma There's already an ENV for etcd, If ZO ever supports TLS listeners it will need a Cert/Key/CA variables.

What threw me off is that there's no errors in the UI when this happens, the error only shows up in the logs. There's also no way to test alerts from the UI.

If I have to build my own image, I will probably never use the alerts features. It adds unnecessary overhead.

**Comment by hengfeiyang** [comment]
will resolve it like `curl -k` to skip cert verify
