### ISSUE TITLE
Table charts are justified to the right

### ISSUE THREAD

**Issue by gaby** [zinclabs/zincobserve#739]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

When creating a table chart with a string field this happens:

![image](https://github.com/zinclabs/zincobserve/assets/835733/3557b621-da88-450b-8388-d1bb099ac4b1)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.4.3
```

**Comment by gaby** [comment]
@prabhatsharma @ktx-kirtan Any progress on this? It makes the data table unsable for dashboards if the text is long

**Comment by prabhatsharma** [comment]
oops. We missed this one. We will get a quick dev release for you.

**Comment by prabhatsharma** [comment]
@gaby Use this image - public.ecr.aws/zinclabs/zincobserve-dev:v0.4.4-97e28e3-amd64

**Comment by gaby** [comment]
@prabhatsharma @ktx-kirtan Will test it out in 1-2hrs :-) thanks!

**Comment by gaby** [comment]
@prabhatsharma @hengfeiyang Did something changed? All the queries return 0 data even though my stream has 800MB. These are the logs:

Logs:
![image](https://github.com/zinclabs/zincobserve/assets/835733/bc587340-fbc1-4348-a6e2-5b4cba873b95)

Streams:

![image](https://github.com/zinclabs/zincobserve/assets/835733/14202413-9ebc-4dd4-ba4c-2fe9430f9161)

**Comment by hengfeiyang** [comment]
@gaby This is a bug #834 can't query data more than 3 days. will release new version soon.

**Comment by gaby** [comment]
@hengfeiyang Yeah, just pulled latest "zincobserve-dev" and I can query data again :-)

**Comment by gaby** [comment]
This can be closed, the original issue is fixed! Thanks!

![image](https://github.com/zinclabs/zincobserve/assets/835733/5841777c-c97b-4160-a5b3-3059a868f339)
