### ISSUE TITLE
PromQL query response error on /range_query API

### ISSUE THREAD

**Issue by hengfeiyang** [zinclabs/zincobserve#747]
- [x] it looks lost WAL data in response, because it often has no latest 5 minutes data
- [x] the value looks doubled 
- [x] range query rate appear negative number(Extrapolation problem)

**Comment by vvv** [comment]
![image](https://github.com/zinclabs/zincobserve/assets/17462/382dd319-d206-40bf-9e11-39a210ae96e2)

@hengfeiyang I've imported the dashboard that you gave me. It reveals a discrepancy between ZincObserve (left) and vanilla Prometheus (right), but I can't correlate it with any of the problems that you've mentioned in the issue title...

**Comment by vvv** [comment]
I've found yet another discrepancy:

Prometheus rejects range query `zo_http_incoming_requests{namespace="ziox-alpha1"}[5m]` sent to `/query_range` API,
```
❯ curl -s --request GET \
  --url 'http://localhost:9090/api/v1/query_range?query=zo_http_incoming_requests%7Bnamespace%3D%22ziox-alpha1%22%7D%5B5m%5D&start=1684269000&end=1684269900&step=15' | jq .
{
  "status": "error",
  "errorType": "bad_data",
  "error": "invalid expression type \"range vector\" for range query, must be Scalar or instant Vector"
}
```

but ZincObserve accepts it.
```
❯ curl -s --request GET \
  --url 'http://localhost:5080/api/default/prometheus/api/v1/query_range?query=zo_http_incoming_requests%7Bnamespace%3D%22ziox-alpha1%22%7D%5B5m%5D&start=1684269000&end=1684269900&step=15' \
  --header 'Authorization: Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=' | jq . | head
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "zo_http_incoming_requests",
          "app": "zinc-observe",
          "endpoint": "/prometheus/api/v1/write",
```

**Comment by vvv** [comment]
> - range query rate appear negative number(Extrapolation problem)

@hengfeiyang #760 fixes one of the bugs related to extrapolation. Another bug is the difference between extrapolation algorithms used by [Prometheus](https://github.com/prometheus/prometheus/blob/b727e69b7601b069ded5c34348dca41b80988f4b/promql/functions.go#L63-L169) and [ZincObserve](https://github.com/zinclabs/zincobserve/blob/f8e1def867ded627c07d64f3fd33b745dce83fe1/src/service/promql/value.rs#L100-L143). I'll fix it tomorrow in the morning.
